/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRC"
 * 	found in "rrc_connection.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_RRCConnection_H_
#define	_RRCConnection_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "UTF8String.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RRCConnection */
typedef struct RRCConnection {
	long	 id;
	UTF8String_t	 name;
	UTF8String_t	 payload;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnection;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnection_H_ */
#include "asn_internal.h"
